# Generated by Django 4.0.4 on 2022-05-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothesitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='laptopitem',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='mobilephoneitem',
            name='color',
        ),
    ]
