# Generated by Django 4.0.4 on 2022-05-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_pay',
            field=models.FloatField(null=True),
        ),
    ]
